server:
  port: 8086
  undertow:
    threads:
      io: 4
      worker: 32
    buffer-size: 1024
    direct-buffers: true
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true

spring:
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:MM:ss
    time-zone: GMT-8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
  mail:
    default-encoding: utf-8
    host: None
    protocol: smtp

  mvc:
    static-path-pattern: /static/**
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chia?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: chia
      password: Chia
      initial-size: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
  mapper-locations: xml/*xml